---
- name: install asusctl
  kewlfft.aur.aur:
    name: asusctl
    state: present

- name: enable and start asusd
  systemd:
    name: asusd
    state: started
    enabled: yes
    masked: no
  become: yes

- name: configure battery charge limit
  shell: "asusctl -c 85"
