---
- name: install gdb and gef
  kewlfft.aur.aur:
    name:
      - gdb
      # - gdb-multiarch
      - gef-git
    state: present

- name: enable gef
  blockinfile:
    path: "/etc/gdb/gdbinit"
    block: |
      source /usr/share/gef/gef.py
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes
