---
- name: install asusctl, supergfxctl, laptop-mode and gpu drivers
  kewlfft.aur.aur:
    name:
      - asusctl
      - supergfxctl
      - laptop-mode-tools
      - nvidia
      - nvidia-utils
      - lib32-nvidia-utils
      - mesa
      - lib32-mesa
    state: present

- name: enable and start asusd
  systemd:
    name: asusd
    state: started
    enabled: yes
    masked: no
  become: yes

- name: enable and start supergfxd
  systemd:
    name: supergfxd
    state: started
    enabled: yes
    masked: no
  become: yes


- name: configure laptop-mode
  blockinfile:
    path: '/etc/laptop-mode/laptop-mode.conf'
    block: |
      HD="{{laptop_hd}}"
      PARTITIONS="auto /"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes

- name: enable and start laptop-mode
  systemd:
    name: laptop-mode
    state: started
    enabled: yes
    masked: no
  become: yes

- name: read asusd.conf
  include_vars:
    file: "/etc/asusd/asusd.conf"
    name: asusd_conf

- name: read supergfxd.conf
  include_vars:
    file: "/etc/supergfxd.conf"
    name: supergfxd_conf

- name: configure battery charge limit
  shell: "asusctl -c {{ bat_charge_limit }}"
  when: "asusd_conf.bat_charge_limit is not defined or
    asusd_conf.bat_charge_limit != bat_charge_limit"

# - name: switch to integrated graphics
#   shell: "supergfxctl -m {{ graphics_mode }}"
#   when: "supergfxd_conf.mode is not defined or
#     supergfxd_conf.mode != graphics_mode"
