---

- name: generate en_GB.UTF-8
  locale_gen:
    name: en_GB.UTF-8
    state: present
  become: yes
- name: generate ru_RU.UTF-8
  locale_gen:
      name: ru_RU.UTF-8
      state: present
  become: yes

- name: set locale
  blockinfile:
    path: /etc/locale.conf
    create: yes
    block: |
      LANG=en_GB.UTF-8
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes
