---
- name: setup locale.gen
  blockinfile:
    path: /etc/locale.gen
    block: |
      en_GB.UTF-8 UTF-8
      ru_RU.UTF-8 UTF-8
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes

- name: generate locales
  shell: locale-gen
  become: yes

- name: set locale
  blockinfile:
    path: /etc/locale.conf
    create: yes
    block: |
      LANG=en_GB.UTF-8
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes
