---
- name: install ly
  kewlfft.aur.aur:
    name: ly
    state: present

- name: enable ly
  systemd:
    name: ly
    enabled: yes
    masked: no
  become: yes

- name: configure ly
  blockinfile:
    path: /etc/ly/config.ini
    block: |
      animate = true
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes
