---
- name: install mpd
  kewlfft.aur.aur:
    name:
      - mpd
      - ncmpcpp
      - python-mpd2
    state: present

- name: enable mpd
  systemd:
    name: mpd
    enabled: yes
    masked: no
  become: yes
