---
- name: install nvim and external programms
  kewlfft.aur.aur:
    name:
      - neovim
      - neovim-plug
      - python-neovim
      # for Coc
      - nodejs
      - npm
      - yarn
      # Coc language servers
      - ccls
      - gopls
      - rust-analyzer
      - texlab
      - pyright
    state: present

- name: update nvim plug
  shell: 
    cmd: "nvim -c 'PlugUpdate | q | q'"
    creates: "/home/{{ username }}/.local/share/nvim/plugged/"
  register: nvim_update_plug
  # changed_when: "'Cloning' in nvim_update_plug.stdout"
