---
- name: install pass and plugins for firefox and git
  kewlfft.aur.aur:
    name:
      - pass
      - pass-git-helper
      - firefox-extension-passff
    state: present

- name: set git credential helper
  ini_file:
    path: "/home/{{ username }}/.gitconfig"
    section: credential
    option: helper
    value: "/usr/bin/pass-git-helper"
