---
- name: install pipewire, extensions and related packages
  loop:
    - pipewire
    - pipewire-pulse
    - pipewire-alsa
    - pipewire-jack
    - pulsemixer
  include_role:
    name: aur_install
