---
- name: clone tabbed
  git:
    repo: https://github.com/falamous/tabbed
    dest: "/home/{{ username }}/src/tabbed"
  register: tabbed

- name: stat /usr/local/bin/tabbed
  stat:
    path: /usr/local/bin/tabbed
  register: bin_tabbed

- name: compile and install tabbed
  make:
    chdir: "/home/{{ username }}/src/tabbed"
    target: install
  when: tabbed.changed or not bin_tabbed.stat.exists
  become: yes
