---
- name: clone tabbed
  git:
    repo: https://github.com/falamous/tabbed
    dest: "/home/{{ username }}/src/tabbed"
  register: tabbed

- name: compile and install tabbed
  make:
    chdir: "/home/{{ username }}/src/tabbed"
    target: install
  when: tabbed.changed
  become: yes
