---
- name: install zsh and extensions
  kewlfft.aur.aur:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present

- name: make zsh the default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  become: yes

- name: create .cache/zsh
  file:
    name: "/home/{{ username }}/.cache/zsh"
    state: directory
