---
- name: install xdg-user-dirs
  community.general.pacman:
    name:
      - xdg-user-dirs
    state: present

- name: copy user-dirs.dirs
  ansible.builtin.copy:
    src: user-dirs.dirs
    dest: "/home/{{ config.general.username }}/.config/"
    mode: "0644"

- name: create .config/npm
  ansible.builtin.file:
    name: "/home/{{ config.general.username }}/.config/npm"
    state: directory
    mode: "0755"

- name: edit npmrc
  ansible.builtin.blockinfile:
    path: "/home/{{ config.general.username }}/.config/npm/npmrc"
    block: |
      prefix=${XDG_DATA_HOME}/npm
      cache=${XDG_CACHE_HOME}/npm
      tmp=${XDG_RUNTIME_DIR}/npm
      init-module=${XDG_CONFIG_HOME}/npm/npm-init.js
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    create: true
    mode: "0644"


- name: create .config/wgetrc
  ansible.builtin.blockinfile:
    path: '/home/{{ config.general.username }}/.config/wgetrc'
    block: "hsts-file = /home/{{ config.general.username }}/.cache/wget-hsts"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
    mode: "0644"

- name: extend zsh env
  ansible.builtin.blockinfile:
    path: "{{ config.general.shellenv }}"
    block: |
      export WINEPREFIX="$XDG_DATA_HOME/wine"
      export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
      export LESSKEY="$XDG_CONFIG_HOME/lesskey"
      export LESSHISTFILE="$XDG_CACHE_HOME/lesshst"
      export WGETRC="$XDG_CONFIG_HOME/wgetrc"

      export SSB_HOME="$XDG_CONFIG_HOME/zoom"

      export GEM_HOME="$XDG_DATA_HOME/gem"
      export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

      export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
      export PYLINTHOME="$XDG_CACHE_HOME/pylint"
      export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
      export DOT_SAGE="$XDG_CONFIG_HOME/sage"

      export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
      export ANDROID_AVD_HOME="$XDG_DATA_HOME/android/"
      export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME/android/"
      export ADB_VENDOR_KEY="$XDG_CONFIG_HOME/android"

      export XINITRC="$XDG_CONFIG_HOME/xinitrc"
      export WGETRC="$XDG_CONFIG_HOME/wgetrc"

      export GEM_HOME="$XDG_DATA_HOME/gem"
      export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

      export ELINKS_CONFDIR="$XDG_CONFIG_HOME/elinks"
      export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

      export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
      export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

      export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

      export GOPATH="$XDG_DATA_HOME/go"
      export CARGO_HOME="$XDG_DATA_HOME/cargo"
      export LESSHISTFILE=-

      export GNUPGHOME="$HOME/share/apps/gpg"

      export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java


    marker: "# {mark} ANSIBLE (xdg) MANAGED BLOCK"
    create: true
    mode: "0644"
