export PATH="$PATH:/opt/cuda/bin/:$HOME/scripts"
export EDITOR="nvim"
export SHELL="/bin/zsh"
# export TERM="st"
export TERM="xterm"
export TERMINAL="tabbed -c alacritty --embed"
export BROWSER="firefox"
export READER="zathura"
export PAGER="less"

export _JAVA_AWT_WM_NONREPARENTING=1 # for ghidra
export AWT_TOOLKIT=MToolKit

export PYTHONSTARTUP="$HOME/scripts/falamous.py"
export PYTHONPATH="$PYTHONPATH:$HOME/scripts/"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export WINEPREFIX="$XDG_DATA_HOME/wine"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export LESSKEY="$XDG_CONFIG_HOME/lesskey"
export LESSHISTFILE="$XDG_CACHE_HOME/lesshst"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
# echo hsts-file \= "$XDG_CACHE_HOME/wget-hsts" >> "$XDG_CONFIG_HOME/wgetrc"
export TELEGRAM_CONFIG_DIR="$XDG_CONFIG_HOME/telegram-cli"
export TELEGRAM_HOME="$XDG_CACHE_HOME"

export SSB_HOME="$XDG_CONFIG_HOME/zoom"

export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

export GNUPGHOME="$XDG_DATA_HOME/gnupg"

export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export DOT_SAGE="$XDG_CONFIG_HOME/sage"

export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export ANDROID_AVD_HOME="$XDG_DATA_HOME/android/"
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME/android/"
export ADB_VENDOR_KEY="$XDG_CONFIG_HOME/android"

export XINITRC="$XDG_CONFIG_HOME/xinitrc"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
# echo hsts-file \= "$XDG_CACHE_HOME"/wget-hsts >> "$XDG_CONFIG_HOME/wgetrc"

export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

export ELINKS_CONFDIR="$XDG_CONFIG_HOME/elinks"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GDBHISTFILE="$XDG_CACHE_HOME/gdb_history"
   
export QT_STYLE_OVERRIDE="kvantum-dark"
export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"

export GOPATH="$XDG_DATA_HOME/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export LESSHISTFILE=-

# disable firefox sandboxing, because fuck sandboxing
export MOZ_DISABLE_GMP_SANDBOX=1
export MOZ_DISABLE_CONTENT_SANDBOX=1

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GNUPGHOME="$XDG_DATA_HOME/gpg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export DEBUGINFOD_URLS="https://debuginfod.archlinux.org/"
export MAKEFLAGS="-j 2"

export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
