#!/bin/sh

sudo pacman -S archiso --noconfirm

ODIR=${1:-./}
WDIR=$(mktemp -d)
PDIR=${2:-$(mktemp -d)}

cp -r /usr/share/archiso/configs/releng/* "$PDIR"

cat >>"/$PDIR/packages.x86_64" <<KEK
python3
python-pip
ansible
python-pwntools
python-requests

radare2
foremost
binwalk

neovim

networkmanager
connman

wine

qemu-full
qemu-arch-extra

gdb

docker

nmap
socat
iputils
bind

lm_sensors
dmidecode
evtest

ripgrep
aria2
lsd
wget
curl
zip
unzip
p7zip
pv
bat
sqlitebrowser
openssh

xorg
xfce4
alacritty
firefox
mpv
sxiv
KEK

cat >>"/$PDIR/pacman.conf" <<KEK
[multilib]
Include = /etc/pacman.d/mirrorlist
KEK

sudo mkarchiso -v -w "$WDIR" -o "$ODIR" "$PDIR"

sudo rm -rf "$WDIR"
sudo rm -rf "$PDIR"
